FROM python:3.8-slim
RUN apt-get update && apt-get install -y docker.io

COPY monitor_and_stop.sh /usr/local/bin

RUN chmod +x /usr/local/bin/monitor_and_stop.sh

CMD ["/usr/local/bin/monitor_and_stop.sh"]
